apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 1m
  chart:
    spec:
      chart: gatekeeper
      version: 3.8.1
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
  values: {}
