apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: '6.29.5'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 1m
  values:
    replicas: 1
