apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: falco
spec:
  interval: 1m
  chart:
    spec:
      chart: falco
      version: 1.18.4
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: falco
  values:
    ebpf:
      enabled: true
