apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: kafka
spec:
  interval: 1m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.29.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: kafka
  values: {}
