apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-simple-scalable
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    serviceAccount:
      annotations: 
        iam.gke.io/gcp-service-account: cluster-monitoring-loki@abrand-playground.iam.gserviceaccount.com
    loki:
      authEnabled: false
      storage:
        type: gcs
        bucketNames:
          chunks: bkt-gke-dev01-logs
          ruler: bkt-gke-dev01-logs
          admin: bkt-gke-dev01-logs
