apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values: {}
