apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: tempo
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    tempo:
      searchEnabled: true